version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
    command: npm start
    image: resume_builder_backendz  # Set the image name
    container_name: resume_builder_containerz  # Set the container name
